### ISSUE TITLE
Can't patch it - Red FATAL message

### ISSUE THREAD

**Issue by azizen12** [taku-nm/auto-cli#20]
Hey!
I'm trying to use the batch to install Relay but the installer messes up somewhere. I don't know if there's any error logs but here's what I can see after editing the notepad and inserting my client ID:

Patching Relay.apk
INFO: Loading patches
INFO: Setting patch options
com.fasterxml.jackson.databind.JsonMappingException: Unrecognized token 'OG_xwodt53oUJrw4uKsFnQ': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"[ {
  "patchName" : "Custom theme",
  "options" : [ {
    "key" : "backgroundColor",
    "value" : "@android:color/black"
  }, {
    "key" : "accentColor",
    "value" : "#ff1ed760"
  }, {
    "key" : "accentPressedColor",
    "value" : "#ff169c46"
  } ]
}, {
  "patchName" : "Custom branding",
  "options" : [ {
    "key" : "appName",
    "value" : "YouTube ReVanced"
  }, {
    "key" : "iconPath",
    "value" : null
  } ]
}, {
  "patchName" : "Theme",
  "options" : [ {
   "[truncated 423 chars]; line: 41, column: 37] (through reference chain: java.lang.Object[][4]->app.revanced.library.Options$Patch["options"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:373)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:375)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:216)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
        at app.revanced.library.Options.deserialize(Options.kt:53)
        at app.revanced.library.Options.setOptions(Options.kt:64)
        at app.revanced.library.Options.setOptions(Options.kt:86)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:202)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'OG_xwodt53oUJrw4uKsFnQ': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"[ {
  "patchName" : "Custom theme",
  "options" : [ {
    "key" : "backgroundColor",
    "value" : "@android:color/black"
  }, {
    "key" : "accentColor",
    "value" : "#ff1ed760"
  }, {
    "key" : "accentPressedColor",
    "value" : "#ff169c46"
  } ]
}, {
  "patchName" : "Custom branding",
  "options" : [ {
    "key" : "appName",
    "value" : "YouTube ReVanced"
  }, {
    "key" : "iconPath",
    "value" : null
  } ]
}, {
  "patchName" : "Theme",
  "options" : [ {
   "[truncated 423 chars]; line: 41, column: 37]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:759)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:3038)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2079)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:805)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:423)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        ... 27 more

  FATAL
  Something must've gone wrong during patching. Contact taku on discord or open an issue on github.
 bat Version 1.40

 Pressing any key will close this window.

Press any key to continue . . .

**Comment by taku-nm** [comment]
This looks like you have incorrect formatting in your json. I suspect you forgot the quotes around the client id.

![Screenshot 2023-10-01 190742](https://github.com/taku-nm/auto-cli/assets/23640508/c204046a-9663-44e6-b32c-8de8bfffe405)

Place it where is says `your_client_id` and make sure to add the quotes around it.

**Comment by azizen12** [comment]
Yep that was it, thanks for the quick answer and a great tool! You're awesome :)
